// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjaooDnbowxr94sb6TlSdc1FBYNR5CC1U',
    appId: '1:54544562344:web:c7e44d1d0a8008a02c2a9d',
    messagingSenderId: '54544562344',
    projectId: 'movaset-f734f',
    authDomain: 'movaset-f734f.firebaseapp.com',
    storageBucket: 'movaset-f734f.firebasestorage.app',
    measurementId: 'G-9S07DWZYY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHIt9QMNMX_u1XAsOOLZBpvQMo3SGpXCw',
    appId: '1:54544562344:android:a1613a9d6b148c1f2c2a9d',
    messagingSenderId: '54544562344',
    projectId: 'movaset-f734f',
    storageBucket: 'movaset-f734f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB48X_g-ZDTiRo0SrCK9GZVjmoA2vot8Y8',
    appId: '1:54544562344:ios:6f28e420634e1ed02c2a9d',
    messagingSenderId: '54544562344',
    projectId: 'movaset-f734f',
    storageBucket: 'movaset-f734f.firebasestorage.app',
    iosBundleId: 'com.example.pbl411',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB48X_g-ZDTiRo0SrCK9GZVjmoA2vot8Y8',
    appId: '1:54544562344:ios:6f28e420634e1ed02c2a9d',
    messagingSenderId: '54544562344',
    projectId: 'movaset-f734f',
    storageBucket: 'movaset-f734f.firebasestorage.app',
    iosBundleId: 'com.example.pbl411',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjaooDnbowxr94sb6TlSdc1FBYNR5CC1U',
    appId: '1:54544562344:web:0c11200a00be83772c2a9d',
    messagingSenderId: '54544562344',
    projectId: 'movaset-f734f',
    authDomain: 'movaset-f734f.firebaseapp.com',
    storageBucket: 'movaset-f734f.firebasestorage.app',
    measurementId: 'G-8FM9NZY2QS',
  );
}
