// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrUL5QECz8r2FG8B3LIvFIxxs2hMJ24Gc',
    appId: '1:255032212598:web:a621987b77225430ce3357',
    messagingSenderId: '255032212598',
    projectId: 'movaset-23aa4',
    authDomain: 'movaset-23aa4.firebaseapp.com',
    databaseURL: 'https://movaset-23aa4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'movaset-23aa4.firebasestorage.app',
    measurementId: 'G-531ZSC36K4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAECRvhvDGi1Oh5wWSpH_mExAdGWo-aFXs',
    appId: '1:255032212598:android:1cf694c279d424cece3357',
    messagingSenderId: '255032212598',
    projectId: 'movaset-23aa4',
    databaseURL: 'https://movaset-23aa4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'movaset-23aa4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSnWUenF8Vwmv6__yxaGeKhuVEQvPimuw',
    appId: '1:255032212598:ios:3cc8de0c8a1bdf9fce3357',
    messagingSenderId: '255032212598',
    projectId: 'movaset-23aa4',
    databaseURL: 'https://movaset-23aa4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'movaset-23aa4.firebasestorage.app',
    iosBundleId: 'com.example.pbl411',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSnWUenF8Vwmv6__yxaGeKhuVEQvPimuw',
    appId: '1:255032212598:ios:3cc8de0c8a1bdf9fce3357',
    messagingSenderId: '255032212598',
    projectId: 'movaset-23aa4',
    databaseURL: 'https://movaset-23aa4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'movaset-23aa4.firebasestorage.app',
    iosBundleId: 'com.example.pbl411',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrUL5QECz8r2FG8B3LIvFIxxs2hMJ24Gc',
    appId: '1:255032212598:web:40b56dab5c7e033cce3357',
    messagingSenderId: '255032212598',
    projectId: 'movaset-23aa4',
    authDomain: 'movaset-23aa4.firebaseapp.com',
    databaseURL: 'https://movaset-23aa4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'movaset-23aa4.firebasestorage.app',
    measurementId: 'G-PVS9LEYZKP',
  );
}
